standardised api endpoint syntax
api now has 3 [status]es, success, fail and error.
success: very good, contains [content] (nullable)
fail: could not finish request, [reason] will be given
error: server blew up
all statuses will be accompanied by [message]

reduced warn level of some calls, e.g. not finding a favourite no longer returns fail
standardised endpoint message creation to single function call

this change is very scorched earth, lemme know if it breaks anything